version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_sales
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_sales
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80" # đổi port nếu cần tránh trùng
    networks:
      - backend
    depends_on:
      - postgres
    restart: always

  redis:
    image: redis:latest
    container_name: redis_sales
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data
    restart: always

  product-service:
    build: ./product-service
    container_name: product_service
    ports:
      - "3001:3001"
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
